name: revealjs-ci

on:
  - push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20
        dir: ["structured-cxx"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        working-directory: ${{ matrix.dir }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.dir }}
      - run: npm test
        env:
          CI: true
        working-directory: ${{ matrix.dir }}
